spring:
  liquibase:
    change-log: classpath:/migration/master-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123456
server:
  port: 8900
jwt:
  secret: your_secret_key
  expiration: 3600000
  accessTokenExpiration: 1800000
  refreshTokenExpiration: 86400000
